name: batufo
description: UFO multi-player game using Flutter.

version: 0.5.1+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: 0.24.0
  protobuf: ^1.0.1
  logging: ^0.11.4
  socket_io_client: ^0.9.10

  equatable: ^1.1.1
  http: ^0.12.1

  audioplayers: ^0.15.1

  material_design_icons_flutter: ^4.0.5345
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4

  url_launcher: 5.4.11

  url_launcher_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: b0794faf2c000576515aee56ca6bb5bee64cece4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg/
    - assets/images/sprites/
    - assets/images/static/
    - assets/images/icons/
    - assets/audio/
